
services:
  db:
    image: mysql:8.0.31
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: times

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8000:80"

volumes:
  dbbase:
